package com.spellchecker.arabickb.utils


object EMOJIS {

    val GRINNING_FACE = "&#128512;"
    val BEAMING_FACE_WITH_SMILING_EYES = "&#128513;"
    val GRINNING_SQUINTING_FACE = "&#128518;"
    val GRINNING_FACE_WITH_SWEAT = "&#128517;"
    val FACE_WITH_TEARS_OF_JOY = "&#128514;"
    val ROLLING_ON_THE_FLOOR_LAUGHING = "&#129315;"
    val SLIGHTLY_SMILING_FACE = "&#128578;"
    val UPSIDE_DOWN_FACE = "&#128579;"
    val WINKING_FACE = "&#128521;"
    val SMILING_FACE_WITH_SMILING_EYES = "&#128522;"
    val FACE_HEART_EMOJI = "&#128525;"
    val STAR_EMOJI = "&#11088;"
    val SMILING_FACE_WITH_HEARTS = "&#129392;"
    val STAR_STRUCK = "&#129321;"
    val FACE_BLOWING_A_KISS = "&#128536;"
    val SMILING_FACE = "&#9786;"
    val SMILING_FACE_WITH_TEAR = "&#129394;"
    val FACE_WITH_TONGUE = "&#128539;"
    val ZANY_FACE = "&#129322;"
    val SQUINTING_FACE_WITH_TONGUE = " &#128541;"
    val HUGGING_FACE = "&#129303;"
    val SHUSHING_FACE = "&#129323;"
    val THINKING_FACE = "&#129300;"
    val FACE_WITH_RAISED_EYEBROW = "&#129320;"
    val EXPRESSIONLESS_FACE = "&#128529;"
    val FACE_WITHOUT_MOUTH = "&#128566;"
    val SMIRKING_FACE = "&#128527;"
    val UNAMUSED_FACE = "&#128530;"
    val WINKING_FACE_WITH_TONGUE = "&#128540;"
    val GRIMACING_FACE = "&#128556;"
    val RELIEVED_FACE = "&#128524;"
    val PENSIVE_FACE = "&#128532;"
    val SLEEPY_FACE = "&#128564;"
    val SLEEPING_FACE = "&#128564;"
    val EXPLODING_HEAD = "&#129327;"
    val PARTYING_FACE = "&#129395;"
    val SMILING_FACE_WITH_SUNGLASSES = "&#128526;"
    val SLIGHTLY_FROWNING_FACE = "&#128577;"
    val HUSHED_FACE = "&#128559;"
    val PLEADING_FACE = "&#129402;"
    val CRYING_FACE = "&#128557;"
    val LOUDLY_CRYING_FACE = "&#128557;"
    val CONFOUNDED_FACE = "&#128534;"
    val DOWNCAST_FACE_WITH_SWEAT = "&#128531;"
    val TIRED_FACE = "&#128555;"
    val YAWNING_FACE = "&#129393;"
    val FACE_WITH_STEAM_FROM_NOSE = "&#128548;"
    val POUTING_FACE = "&#128545;"
    val ANGRY_FACE = "&#128544;"
    val SKULL_AND_CROSSBONES = "&#9760;"
    val PILE_OF_POO = "&#128169;"
    val CLOWN_FACE = "&#129313;"
    val GHOST = "&#128123;"
    val GRINNING_CAT_WITH_SMILING_EYES = "&#128568;"
    val CAT_WITH_TEARS_OF_JOY = "&#128569;"
    val SMILING_CAT_WITH_HEART_EYES = "&#128571;"
    val CAT_WITH_WRY_SMILE = "&#128572;"
    val KISSING_CAT = "&#128573;"
    val WEARY_CAT = "&#128576;"
    val CRYING_CAT = "&#128575;"
    val POUTING_CAT = "&#128574;"
    val SEE_NO_EVIL_MONKEY = "&#128584;"
    val HEAR_NO_EVIL_MONKEY = "&#128585;"
    val SPEAK_NO_EVIL_MONKEY = "&#128586;"
    val GROWING_HEART = "&#128151;"
    val TWO_HEARTS = "&#128149;"
    val HEART_EXCLAMATION = "&#10083;"  //&#10083;&#65039;
    val RED_HEART = "&#10084;"
    val ORANGE_HEART = "&#129505;"
    val YELLOW_HEART = "&#128155;"
    val GREEN_HEART = "&#128154;"
    val BLUE_HEART = "&#128153;"
    val PURPLE_HEART = "&#128156;"
    val BLACK_HEART = "&#128420;"
    val HUNDRED_POINTS = "&#128175;"
    val COLLISION = "&#128165;"
    val SWEAT_DROPLETS = "&#128166;"
    val DASHING_AWAY = "&#128168;"
    val BOMB = "&#128163;"
    val SPEECH_BALLOON = "&#128172;"
    val WAVING_HAND = "&#128075;"
    val RAISED_BACK_OF_HAND = "&#129306;"
    val VICTORY_HAND = "&#9996;"
    val SIGN_OF_THE_HORNS = "&#129304;"
    val BACKHAND_INDEX_POINTING_LEFT = "&#128072;"
    val BACKHAND_INDEX_POINTING_RIGHT = "&#128073;"
    val THUMBS_UP = "&#128077;"
    val THUMBS_DOWN = "&#128078;"
    val MIDDLE_FINGER = "&#128405;"
    val ONCOMING_FIST = "&#128074;"
    val LEFT_FACING_FIST = "&#129307;"
    val RIGHT_FACING_FIST = "&#129308;"
    val CLAPPING_HANDS = "&#128079;"
    val RAISING_HANDS = "&#128588;"
    val HANDSHAKE = "&#129309;"
    val FOLDED_HANDS = "&#128591;"
    val FLEXED_BICEPS = "&#128170;"
    val BRAIN = "&#129504;"
    val EYES = "&#128064;"
    val BIRTHDAY_CAKE = "&#127874;"
    val SHORTCAKE = "&#127856;"

    val emojis = arrayListOf(
        GRINNING_FACE,
        BEAMING_FACE_WITH_SMILING_EYES,
        GRINNING_SQUINTING_FACE,
        GRINNING_FACE_WITH_SWEAT,
        FACE_WITH_TEARS_OF_JOY,
        ROLLING_ON_THE_FLOOR_LAUGHING,
        SLIGHTLY_SMILING_FACE,
        UPSIDE_DOWN_FACE,
        WINKING_FACE,
        SMILING_FACE_WITH_SMILING_EYES,
        FACE_HEART_EMOJI,
        SMILING_FACE_WITH_HEARTS,
        STAR_STRUCK,
        FACE_BLOWING_A_KISS,
        SMILING_FACE,
        SMILING_FACE_WITH_TEAR,
        FACE_WITH_TONGUE,
        ZANY_FACE,
        SQUINTING_FACE_WITH_TONGUE,
        HUGGING_FACE,
        SHUSHING_FACE,
        THINKING_FACE,
        FACE_WITH_RAISED_EYEBROW,
        EXPRESSIONLESS_FACE,
        FACE_WITHOUT_MOUTH,
        SMIRKING_FACE,
        STAR_EMOJI,
        UNAMUSED_FACE,
        WINKING_FACE_WITH_TONGUE,
        GRIMACING_FACE,
        RELIEVED_FACE,
        PENSIVE_FACE,
        SLEEPY_FACE,
        SLEEPING_FACE,
        EXPLODING_HEAD,
        PARTYING_FACE,
        SMILING_FACE_WITH_SUNGLASSES,
        SLIGHTLY_FROWNING_FACE,
        HUSHED_FACE,
        PLEADING_FACE,
        CRYING_FACE,
        LOUDLY_CRYING_FACE,
        CONFOUNDED_FACE,
        DOWNCAST_FACE_WITH_SWEAT,
        TIRED_FACE,
        YAWNING_FACE,
        FACE_WITH_STEAM_FROM_NOSE,
        POUTING_FACE,
        ANGRY_FACE,
        SKULL_AND_CROSSBONES,
        PILE_OF_POO,
        CLOWN_FACE,
        GHOST,
        GRINNING_CAT_WITH_SMILING_EYES,
        CAT_WITH_TEARS_OF_JOY,
        SMILING_CAT_WITH_HEART_EYES,
        CAT_WITH_WRY_SMILE,
        KISSING_CAT,
        WEARY_CAT,
        CRYING_CAT,
        POUTING_CAT,
        SEE_NO_EVIL_MONKEY,
        HEAR_NO_EVIL_MONKEY,
        SPEAK_NO_EVIL_MONKEY,
        GROWING_HEART,
        TWO_HEARTS,
        HEART_EXCLAMATION,
        RED_HEART,
        ORANGE_HEART,
        YELLOW_HEART,
        GREEN_HEART,
        BLUE_HEART,
        PURPLE_HEART,
        BLACK_HEART,
        HUNDRED_POINTS,
        COLLISION,
        SWEAT_DROPLETS,
        DASHING_AWAY,
        BOMB,
        SPEECH_BALLOON,
        WAVING_HAND,
        RAISED_BACK_OF_HAND,
        VICTORY_HAND,
        SIGN_OF_THE_HORNS,
        BACKHAND_INDEX_POINTING_LEFT,
        BACKHAND_INDEX_POINTING_RIGHT,
        THUMBS_UP,
        THUMBS_DOWN,
        MIDDLE_FINGER,
        COLLISION,
        ONCOMING_FIST,
        LEFT_FACING_FIST,
        RIGHT_FACING_FIST,
        CLAPPING_HANDS,
        RAISING_HANDS,
        HANDSHAKE,
        FOLDED_HANDS,
        FLEXED_BICEPS,
        BRAIN,
        EYES,
        BIRTHDAY_CAKE,
        SHORTCAKE
    )
}