package com.spellchecker.arabickb.utils

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.os.Build
import android.widget.Toast
import com.spellchecker.arabickb.R

object LangSelection {
    val Flagimg = intArrayOf(
        R.drawable.afrikaans,
        R.drawable.amharic,
        R.drawable.arabic,
        R.drawable.armenian,
        R.drawable.azerbaycan,
        R.drawable.basque,
        R.drawable.bengali,
        R.drawable.bulgarian,
        R.drawable.catalan,
        R.drawable.croatian,
        R.drawable.czech,
        R.drawable.chinese,
        R.drawable.danish,
        R.drawable.dutch,
        R.drawable.english,
        R.drawable.esperanto,
        R.drawable.estonian,
        R.drawable.filipino,
        R.drawable.french,
        R.drawable.finnish,
        R.drawable.galician,
        R.drawable.georgian,
        R.drawable.gujarati,
        R.drawable.german,
        R.drawable.greek,
        R.drawable.hebrew,
        R.drawable.hindi,
        R.drawable.hungarian,
        R.drawable.indonesian,
        R.drawable.icelandic,
        R.drawable.italian,
        R.drawable.javanese,
        R.drawable.japanese,
        R.drawable.kannada,
        R.drawable.khmer,   //latin
        R.drawable.korean,
        R.drawable.lao,
        R.drawable.latvian,
        R.drawable.lao,
        R.drawable.irish,
        R.drawable.lithuanian,
        R.drawable.malay,
        R.drawable.malayalam,
        R.drawable.moldavian,
        R.drawable.marathi,
        R.drawable.nepali,
        R.drawable.norwegian,
        R.drawable.persian,
        R.drawable.punjabi,
        R.drawable.pashto,
        R.drawable.polish,
        R.drawable.portuguese,
        R.drawable.romanian,
        R.drawable.russian,
        R.drawable.sinhala,
        R.drawable.slovak,
        R.drawable.slovenian,
        R.drawable.spanish,
        R.drawable.sundanese,
        R.drawable.swahili,
        R.drawable.swedish,
        R.drawable.serbian,
        R.drawable.tamil,
        R.drawable.telugu,
        R.drawable.thai,
        R.drawable.turkish,
        R.drawable.ukrainian,
        R.drawable.urdu,
        R.drawable.vietnamese,
        R.drawable.zulu
    )
    var Lang = arrayListOf(

        Languages( R.drawable.afrikaans,"Afrikaans"),
        Languages(  R.drawable.amharic,"Amharic"),
        Languages(    R.drawable.arabic,"Arabic"),
        Languages(   R.drawable.armenian,"Armenian"),
        Languages(    R.drawable.azerbaycan,"Azerbaycan"),
        Languages(  R.drawable.basque,"Basque"),
        Languages(  R.drawable.bengali,"Bangla"),
        Languages(  R.drawable.bulgarian,"Bulgarian"),
        Languages(   R.drawable.catalan,"Catalan"),
        Languages(   R.drawable.croatian,"Croatian"),
        Languages(    R.drawable.czech,"Czech"),
        Languages(  R.drawable.chinese,"Chinese"),
        Languages(   R.drawable.danish,"Danish"),
        Languages(    R.drawable.dutch,"Dutch"),
        Languages(   R.drawable.english,"English"),
         Languages(   R.drawable.esperanto,"Esperanto"),
        Languages( R.drawable.estonian,"Estonian"),
        Languages( R.drawable.filipino,"Filipino"),
        Languages(     R.drawable.french,"French"),
        Languages(  R.drawable.finnish,"Finnish"),
        Languages( R.drawable.galician,"Galician"),
        Languages(  R.drawable.georgian,"Georgian"),
        Languages( R.drawable.gujarati,"Gujarati"),
        Languages(   R.drawable.german,"German"),
        Languages(   R.drawable.greek,"Greek"),
        Languages( R.drawable.hebrew,"Hebrew"),
        Languages(  R.drawable.hindi,"Hindi"),
        Languages( R.drawable.hungarian,"Hungarian"),
        Languages(  R.drawable.indonesian,"Indonesian"),
        Languages( R.drawable.icelandic,"Icelandic"),
        Languages( R.drawable.italian,"Italian"),
        Languages( R.drawable.javanese, "Javanese"),
        Languages( R.drawable.japanese,"Japanese"),
        Languages(  R.drawable.kannada,"Kannada"),
        Languages( R.drawable.khmer,"Khmer"),
        Languages(R.drawable.korean,"Korean"),
        Languages(  R.drawable.lao,"Latin"),
        Languages(R.drawable.latvian,"Latvian"),
        Languages(R.drawable.lao,"Lao"),
        Languages( R.drawable.irish,"Irish"),
        Languages(   R.drawable.lithuanian,"Lithuanian"),
        Languages(     R.drawable.malay,"Malay"),
        Languages( R.drawable.malayalam,"Malayalam"),
        Languages( R.drawable.moldavian,"Moldavian"),
        Languages(   R.drawable.marathi,"Marathi"),
        Languages(R.drawable.nepali,"Nepali"),
        Languages(R.drawable.norwegian, "Norwegian"),
        Languages(R.drawable.persian,"Persian"),
        Languages( R.drawable.punjabi,"Punjabi"),
        Languages( R.drawable.pashto,"Pashto"),
        Languages( R.drawable.polish,"Polish"),
        Languages(  R.drawable.portuguese,"Portuguese"),
        Languages(   R.drawable.romanian,"Romanian"),
        Languages(R.drawable.russian,"Russian"),
        Languages( R.drawable.sinhala,"Sinhala"),
        Languages(    R.drawable.slovak,"Slovak"),
        Languages(  R.drawable.slovenian,"Slovenian"),
        Languages(  R.drawable.spanish,"Spanish"),
        Languages(  R.drawable.sundanese,"Sundanese"),
        Languages(R.drawable.swahili,"Swahili"),
        Languages( R.drawable.swedish,"Swedish"),
        Languages( R.drawable.serbian,"Serbian"),
        Languages(R.drawable.tamil,"Tamil"),
        Languages(   R.drawable.telugu,"Telugu"),
        Languages(   R.drawable.thai,"Thai"),
        Languages( R.drawable.turkish,"Turkish"),
        Languages(  R.drawable.ukrainian,"Ukrainian"),
        Languages( R.drawable.urdu,"Urdu"),
        Languages(    R.drawable.vietnamese,"Vietnamese"),
        Languages(  R.drawable.zulu,"Zulu")
    ,

    )
    var Langnames= arrayOf(
        "Afrikaans",
        "Amharic",
        "Arabic",
        "Armenian",
        "Azerbaycan",
        "Basque",
        "Bangla",
        "Bulgarian",
        "Catalan",
        "Croatian",
        "Czech",
        "Chinese",
        "Danish",
        "Dutch",
        "English",
        "Esperanto",
        "Estonian",
        "Filipino",
        "French",
        "Finnish",
        "Galician",
        "Georgian",
        "Gujarati",
        "German",
        "Greek",
        "Hebrew",
        "Hindi",
        "Hungarian",
        "Indonesian",
        "Icelandic",
        "Italian",
        "Javanese",
        "Japanese",
        "Kannada",
        "Khmer",
        "Korean",
        "Latin",
        "Latvian",
        "Lao",
        "Irish",
        "Lithuanian",
        "Malay",
        "Malayalam",
        "Moldavian",
        "Marathi",
        "Nepali",
        "Norwegian",
        "Persian",
        "Punjabi",
        "Pashto",
        "Polish",
        "Portuguese",
        "Romanian",
        "Russian",
        "Sinhala",
        "Slovak",
        "Slovenian",
        "Spanish",
        "Sundanese",
        "Swahili",
        "Swedish",
        "Serbian",
        "Tamil",
        "Telugu",
        "Thai",
        "Turkish",
        "Ukrainian",
        "Urdu",
        "Vietnamese",
        "Zulu"
    )
    var Langcode= arrayOf(
        "af-ZA",
        "am-ET",
        "ar-SA",
        "hy-AM",
        "az-AZ",
        "eu-ES",
        "bn-BD",
        "bg-BG",
        "ca-ES",
        "hr-HR",
        "cs-CZ",
        "zh",
        "da-DK",
        "nl-NL",
        "en-GB",
        "eo",
        "et",
        "fil-PH",
        "fr-FR",
        "fi-FI",
        "gl-ES",
        "ka-GE",
        "gu-IN",
        "de-DE",
        "el-GR",
        "he-IL",
        "hi-IN",
        "hu-HU",
        "id-ID",
        "is-IS",
        "it-IT",
        "jv-ID",
        "ja-JP",
        "kn-IN",
        "km-KH",
        "ko-KR",
        "la",
        "lv-LV",
        "lo-LA",
        "ga",
        "lt-LT",
        "ms-MY",
        "ml-IN",
        "mo",
        "mr-IN",
        "ne-NP",
        "nb-NO",
        "fa-IR",
        "pa",
        "ps",
        "pl-PL",
        "pt-PT",
        "ro-RO",
        "ru-RU",
        "si-LK",
        "sk-SK",
        "sl-SI",
        "es-ES",
        "su-ID",
        "sw-TZ",
        "sv-SE",
        "sr-RS",
        "ta-IN",
        "te-IN",
        "th-TH",
        "tr-TR",
        "uk-UA",
        "ur-PK",
        "vi-VN",
        "zu-ZA"
    )

    fun setClipboard(context: Context, text: String) {
        if (text.isEmpty()) {
        } else {
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB) {
                val clipboard =
                    context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                clipboard.text = text
                Toast.makeText(context, "Copied Text", Toast.LENGTH_SHORT).show()
            } else {
                val clipboard =
                    context.getSystemService(Context.CLIPBOARD_SERVICE) as android.content.ClipboardManager
                val clip = ClipData.newPlainText("Copied Text", text)
                clipboard.setPrimaryClip(clip)
                Toast.makeText(context, "Copied Text", Toast.LENGTH_SHORT).show()
            }
        }
    }
}